language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head

services:
  - mongodb
before_script:
  - cp config/mongoid.yml.sample config/mongoid.yml
script:
  - bundle exec rspec spec
